const countriesWithCode = [
  {
    countryName: 'Austria',
    countryCode: '43',
    countryIsoCode: 'AT',
    states: [
      'Burgenland',
      'Kaernten',
      'Niederoesterreich',
      'Oberoesterreich',
      'Salzburg',
      'Steiermark',
      'Tirol',
      'Vorarlberg',
      'Wien',
    ],
  },
  {
    countryName: 'Armenia',
    countryCode: '374',
    countryIsoCode: 'AM',
    states: [
      'Aragatsotn',
      'Ararat',
      'Armavir',
      'Gegharkunik',
      'Kotayk',
      'Lori',
      'Shirak',
      'Syunik',
      'Tavush',
      'Vayots Dzor',
      'Yerevan',
    ],
  },
  {
    countryName: 'Belarus',
    countryCode: '375',
    countryIsoCode: 'BY',
    states: [
      'Brest',
      'Homyel',
      'Horad Minsk',
      'Hrodna',
      'Mahilyow',
      'Minsk',
      'Vitsyebsk',
    ],
  },
  {
    countryName: 'Brazil',
    countryCode: '55',
    countryIsoCode: 'BR',
    states: [
      'Acre',
      'Alagoas',
      'Amapa',
      'Amazonas',
      'Bahia',
      'Ceara',
      'Distrito Federal',
      'Espirito Santo',
      'Goias',
      'Maranhao',
      'Mato Grosso',
      'Mato Grosso do Sul',
      'Minas Gerais',
      'Para',
      'Paraiba',
      'Parana',
      'Pernambuco',
      'Piaui',
      'Rio de Janeiro',
      'Rio Grande do Norte',
      'Rio Grande do Sul',
      'Rondonia',
      'Roraima',
      'Santa Catarina',
      'Sao Paulo',
      'Sergipe',
      'Tocantins',
    ],
  },
  {
    countryName: 'Bulgaria',
    countryCode: '359',
    countryIsoCode: 'BG',
    states: [
      'Blagoevgrad',
      'Burgas',
      'Dobrich',
      'Gabrovo',
      'Khaskovo',
      'Kurdzhali',
      'Kyustendil',
      'Lovech',
      'Montana',
      'Pazardzhik',
      'Pernik',
      'Pleven',
      'Plovdiv',
      'Razgrad',
      'Ruse',
      'Shumen',
      'Silistra',
      'Sliven',
      'Smolyan',
      'Sofiya',
      'Sofiya-Grad',
      'Stara Zagora',
      'Turgovishte',
      'Varna',
      'Veliko Turnovo',
      'Vidin',
      'Vratsa',
      'Yambol',
    ],
  },
  {
    countryName: 'Canada',
    countryCode: '1',
    countryIsoCode: 'CA',
    states: [
      'Alberta',
      'British Columbia',
      'Manitoba',
      'New Brunswick',
      'Newfoundland and Labrador',
      'Northwest Territories',
      'Nova Scotia',
      'Nunavut',
      'Ontario',
      'Prince Edward Island',
      'Quebec',
      'Saskatchewan',
      'Yukon Territory',
    ],
  },
  {
    countryName: 'China',
    countryCode: '86',
    countryIsoCode: 'CN',
    states: [
      'Anhui',
      'Fujian',
      'Gansu',
      'Guangdong',
      'Guizhou',
      'Hainan',
      'Hebei',
      'Heilongjiang',
      'Henan',
      'Hubei',
      'Hunan',
      'Jiangsu',
      'Jiangxi',
      'Jilin',
      'Liaoning',
      'Qinghai',
      'Shaanxi',
      'Shandong',
      'Shanxi',
      'Sichuan',
      'Yunnan',
      'Zhejiang',
      'Guangxi',
      'Nei Mongol',
      'Ningxia',
      'Xinjiang',
      'Xizang (Tibet)',
      'Beijing',
      'Chongqing',
      'Shanghai',
      'Tianjin',
    ],
  },
  {
    countryName: 'Cyprus',
    countryCode: '357',
    countryIsoCode: 'CY',
    states: ['Famagusta', 'Kyrenia', 'Larnaca', 'Limassol', 'Nicosia', 'Paphos'],
  },
  {
    countryName: 'Czech Republic',
    countryCode: '420',
    countryIsoCode: 'CZ',
    states: [
      'Jihocesky Kraj',
      'Jihomoravsky Kraj',
      'Karlovarsky Kraj',
      'Kralovehradecky Kraj',
      'Liberecky Kraj',
      'Moravskoslezsky Kraj',
      'Olomoucky Kraj',
      'Pardubicky Kraj',
      'Plzensky Kraj',
      'Praha',
      'Stredocesky Kraj',
      'Ustecky Kraj',
      'Vysocina',
      'Zlinsky Kraj',
    ],
  },
  {
    countryName: 'Denmark',
    countryCode: '45',
    countryIsoCode: 'DK',
    states: [
      'Arhus',
      'Bornholm',
      'Frederiksberg',
      'Frederiksborg',
      'Fyn',
      'Kobenhavn',
      'Kobenhavns',
      'Nordjylland',
      'Ribe',
      'Ringkobing',
      'Roskilde',
      'Sonderjylland',
      'Storstrom',
      'Vejle',
      'Vestsjalland',
      'Viborg',
    ],
  },
  {
    countryName: 'Estonia',
    countryCode: '372',
    countryIsoCode: 'EE',
    states: [
      'Harjumaa (Tallinn)',
      'Hiiumaa (Kardla)',
      'Ida-Virumaa (Johvi)',
      'Jarvamaa (Paide)',
      'Jogevamaa (Jogeva)',
      'Laanemaa (Haapsalu)',
      'Laane-Virumaa (Rakvere)',
      'Parnumaa (Parnu)',
      'Polvamaa (Polva)',
      'Raplamaa (Rapla)',
      'Saaremaa (Kuressaare)',
      'Tartumaa (Tartu)',
      'Valgamaa (Valga)',
      'Viljandimaa (Viljandi)',
      'Vorumaa (Voru)',
    ],
  },
  {
    countryName: 'Finland',
    countryCode: '358',
    countryIsoCode: 'FI',
    states: [
      'Aland',
      'Etela-Suomen Laani',
      'Ita-Suomen Laani',
      'Lansi-Suomen Laani',
      'Lappi',
      'Oulun Laani',
    ],
  },
  {
    countryName: 'France',
    countryCode: '33',
    countryIsoCode: 'FR',
    states: [
      'Alsace',
      'Aquitaine',
      'Auvergne',
      'Basse-Normandie',
      'Bourgogne',
      'Bretagne',
      'Centre',
      'Champagne-Ardenne',
      'Corse',
      'Franche-Comte',
      'Haute-Normandie',
      'Ile-de-France',
      'Languedoc-Roussillon',
      'Limousin',
      'Lorraine',
      'Midi-Pyrenees',
      'Nord-Pas-de-Calais',
      'Pays de la Loire',
      'Picardie',
      'Poitou-Charentes',
      'Provence-Alpes-Cote d Azur',
      'Rhone-Alpes',
    ],
  },
  { countryName: 'Georgia', countryCode: '995', countryIsoCode: 'GE', states: [] },
  {
    countryName: 'Germany',
    countryCode: '49',
    countryIsoCode: 'DE',
    states: [
      'Baden-Wuerttemberg',
      'Bayern',
      'Berlin',
      'Brandenburg',
      'Bremen',
      'Hamburg',
      'Hessen',
      'Mecklenburg-Vorpommern',
      'Niedersachsen',
      'Nordrhein-Westfalen',
      'Rheinland-Pfalz',
      'Saarland',
      'Sachsen',
      'Sachsen-Anhalt',
      'Schleswig-Holstein',
      'Thueringen',
    ],
  },
  {
    countryName: 'India',
    countryCode: '91',
    countryIsoCode: 'IN',
    states: [
      'Andaman and Nicobar Islands',
      'Andhra Pradesh',
      'Arunachal Pradesh',
      'Assam',
      'Bihar',
      'Chandigarh',
      'Chhattisgarh',
      'Dadra and Nagar Haveli',
      'Daman and Diu',
      'Delhi',
      'Goa',
      'Gujarat',
      'Haryana',
      'Himachal Pradesh',
      'Jammu and Kashmir',
      'Jharkhand',
      'Karnataka',
      'Kerala',
      'Lakshadweep',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Nagaland',
      'Orissa',
      'Pondicherry',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Tripura',
      'Uttaranchal',
      'Uttar Pradesh',
      'West Bengal',
    ],
  },
  {
    countryName: 'Israel',
    countryCode: '972',
    countryIsoCode: 'IL',
    states: ['Central', 'Haifa', 'Jerusalem', 'Northern', 'Southern', 'Tel Aviv'],
  },
  {
    countryName: 'Italy',
    countryCode: '39',
    countryIsoCode: 'IT',
    states: [
      'Abruzzo',
      'Basilicata',
      'Calabria',
      'Campania',
      'Emilia-Romagna',
      'Friuli-Venezia Giulia',
      'Lazio',
      'Liguria',
      'Lombardia',
      'Marche',
      'Molise',
      'Piemonte',
      'Puglia',
      'Sardegna',
      'Sicilia',
      'Toscana',
      'Trentino-Alto Adige',
      'Umbria',
      'Valle d Aosta',
      'Veneto',
    ],
  },
  {
    countryName: 'Kazakhstan',
    countryCode: '7',
    countryIsoCode: 'KZ',
    states: [
      'Almaty Oblysy',
      'Almaty Qalasy',
      'Aqmola Oblysy',
      'Aqtobe Oblysy',
      'Astana Qalasy',
      'Atyrau Oblysy',
      'Batys Qazaqstan Oblysy',
      'Bayqongyr Qalasy',
      'Mangghystau Oblysy',
      'Ongtustik Qazaqstan Oblysy',
      'Pavlodar Oblysy',
      'Qaraghandy Oblysy',
      'Qostanay Oblysy',
      'Qyzylorda Oblysy',
      'Shyghys Qazaqstan Oblysy',
      'Soltustik Qazaqstan Oblysy',
      'Zhambyl Oblysy',
    ],
  },
  {
    countryName: 'Kyrgyz Republic',
    countryCode: '996',
    countryIsoCode: 'KG',
    states: [
      'Batken Oblasty',
      'Bishkek Shaary',
      'Chuy Oblasty',
      'Jalal-Abad Oblasty',
      'Naryn Oblasty',
      'Osh Oblasty',
      'Talas Oblasty',
      'Ysyk-Kol Oblasty',
    ],
  },
  {
    countryName: 'Latvia',
    countryCode: '371',
    countryIsoCode: 'LV',
    states: [
      'Aizkraukles Rajons',
      'Aluksnes Rajons',
      'Balvu Rajons',
      'Bauskas Rajons',
      'Cesu Rajons',
      'Daugavpils',
      'Daugavpils Rajons',
      'Dobeles Rajons',
      'Gulbenes Rajons',
      'Jekabpils Rajons',
      'Jelgava',
      'Jelgavas Rajons',
      'Jurmala',
      'Kraslavas Rajons',
      'Kuldigas Rajons',
      'Liepaja',
      'Liepajas Rajons',
      'Limbazu Rajons',
      'Ludzas Rajons',
      'Madonas Rajons',
      'Ogres Rajons',
      'Preilu Rajons',
      'Rezekne',
      'Rezeknes Rajons',
      'Riga',
      'Rigas Rajons',
      'Saldus Rajons',
      'Talsu Rajons',
      'Tukuma Rajons',
      'Valkas Rajons',
      'Valmieras Rajons',
      'Ventspils',
      'Ventspils Rajons',
    ],
  },
  {
    countryName: 'Mexico',
    countryCode: '52',
    countryIsoCode: 'MX',
    states: [
      'Aguascalientes',
      'Baja California',
      'Baja California Sur',
      'Campeche',
      'Chiapas',
      'Chihuahua',
      'Coahuila de Zaragoza',
      'Colima',
      'Distrito Federal',
      'Durango',
      'Guanajuato',
      'Guerrero',
      'Hidalgo',
      'Jalisco',
      'Mexico',
      'Michoacan de Ocampo',
      'Morelos',
      'Nayarit',
      'Nuevo Leon',
      'Oaxaca',
      'Puebla',
      'Queretaro de Arteaga',
      'Quintana Roo',
      'San Luis Potosi',
      'Sinaloa',
      'Sonora',
      'Tabasco',
      'Tamaulipas',
      'Tlaxcala',
      'Veracruz-Llave',
      'Yucatan',
      'Zacatecas',
    ],
  },
  {
    countryName: 'Republic of Moldova',
    countryCode: '373',
    countryIsoCode: 'MD',
    states: [
      'Anenii Noi',
      'Basarabeasca',
      'Briceni',
      'Cahul',
      'Cantemir',
      'Calarasi',
      'Causeni',
      'Cimislia',
      'Criuleni',
      'Donduseni',
      'Drochia',
      'Dubasari',
      'Edinet',
      'Falesti',
      'Floresti',
      'Glodeni',
      'Hincesti',
      'Ialoveni',
      'Leova',
      'Nisporeni',
      'Ocnita',
      'Orhei',
      'Rezina',
      'Riscani',
      'Singerei',
      'Soldanesti',
      'Soroca',
      'Stefan-Voda',
      'Straseni',
      'Taraclia',
      'Telenesti',
      'Ungheni',
      'Balti',
      'Bender',
      'Chisinau',
      'Gagauzia',
      'Stinga Nistrului',
    ],
  },
  {
    countryName: 'Mongolia',
    countryCode: '976',
    countryIsoCode: 'MN',
    states: [
      'Arhangay',
      'Bayanhongor',
      'Bayan-Olgiy',
      'Bulgan',
      'Darhan Uul',
      'Dornod',
      'Dornogovi',
      'Dundgovi',
      'Dzavhan',
      'Govi-Altay',
      'Govi-Sumber',
      'Hentiy',
      'Hovd',
      'Hovsgol',
      'Omnogovi',
      'Orhon',
      'Ovorhangay',
      'Selenge',
      'Suhbaatar',
      'Tov',
      'Ulaanbaatar',
      'Uvs',
    ],
  },
  {
    countryName: 'Netherlands',
    countryCode: '31',
    countryIsoCode: 'NL',
    states: [
      'Drenthe',
      'Flevoland',
      'Friesland',
      'Gelderland',
      'Groningen',
      'Limburg',
      'Noord-Brabant',
      'Noord-Holland',
      'Overijssel',
      'Utrecht',
      'Zeeland',
      'Zuid-Holland',
    ],
  },
  {
    countryName: 'Poland',
    countryCode: '48',
    countryIsoCode: 'PL',
    states: [
      'Greater Poland (Wielkopolskie)',
      'Kuyavian-Pomeranian (Kujawsko-Pomorskie)',
      'Lesser Poland (Malopolskie)',
      'Lodz (Lodzkie)',
      'Lower Silesian (Dolnoslaskie)',
      'Lublin (Lubelskie)',
      'Lubusz (Lubuskie)',
      'Masovian (Mazowieckie)',
      'Opole (Opolskie)',
      'Podlasie (Podlaskie)',
      'Pomeranian (Pomorskie)',
      'Silesian (Slaskie)',
      'Subcarpathian (Podkarpackie)',
      'Swietokrzyskie (Swietokrzyskie)',
      'Warmian-Masurian (Warminsko-Mazurskie)',
      'West Pomeranian (Zachodniopomorskie)',
    ],
  },
  {
    countryName: 'Romania',
    countryCode: '40',
    countryIsoCode: 'RO',
    states: [
      'Alba',
      'Arad',
      'Arges',
      'Bacau',
      'Bihor',
      'Bistrita-Nasaud',
      'Botosani',
      'Braila',
      'Brasov',
      'Bucuresti',
      'Buzau',
      'Calarasi',
      'Caras-Severin',
      'Cluj',
      'Constanta',
      'Covasna',
      'Dimbovita',
      'Dolj',
      'Galati',
      'Gorj',
      'Giurgiu',
      'Harghita',
      'Hunedoara',
      'Ialomita',
      'Iasi',
      'Ilfov',
      'Maramures',
      'Mehedinti',
      'Mures',
      'Neamt',
      'Olt',
      'Prahova',
      'Salaj',
      'Satu Mare',
      'Sibiu',
      'Suceava',
      'Teleorman',
      'Timis',
      'Tulcea',
      'Vaslui',
      'Vilcea',
      'Vrancea',
    ],
  },
  {
    countryName: 'Russia',
    countryCode: '7',
    countryIsoCode: 'RU',
    states: [
      'Amur',
      'Arkhangelsk',
      'Astrakhan',
      'Belgorod',
      'Bryansk',
      'Chelyabinsk',
      'Chita',
      'Irkutsk',
      'Ivanovo',
      'Kaliningrad',
      'Kaluga',
      'Kamchatka',
      'Kemerovo',
      'Kirov',
      'Kostroma',
      'Kurgan',
      'Kursk',
      'Leningrad',
      'Lipetsk',
      'Magadan',
      'Murmansk',
      'Nizhniy Novgorod',
      'Novgorod',
      'Novosibirsk',
      'Omsk',
      'Orenburg',
      'Orel',
      'Penza',
      'Perm',
      'Pskov',
      'Rostov',
      'Ryazan',
      'Sakhalin',
      'Samara',
      'Saratov',
      'Smolensk',
      'Sverdlovsk',
      'Tambov',
      'Tomsk',
      'Tula',
      'Tver',
      'Tyumen',
      'Ulyanovsk',
      'Vladimir',
      'Volgograd',
      'Vologda',
      'Voronezh',
      'Yaroslavl',
      'Adygeya',
      'Altay',
      'Bashkortostan',
      'Buryatiya',
      'Chechnya',
      'Chuvashiya',
      'Dagestan',
      'Ingushetiya',
      'Kabardino-Balkariya',
      'Kalmykiya',
      'Karachayevo-Cherkesiya',
      'Kareliya',
      'Khakasiya',
      'Komi',
      'Mariy-El',
      'Mordoviya',
      'Sakha',
      'North Ossetia',
      'Tatarstan',
      'Tyva',
      'Udmurtiya',
      'Aga Buryat',
      'Chukotka',
      'Evenk',
      'Khanty-Mansi',
      'Komi-Permyak',
      'Koryak',
      'Nenets',
      'Taymyr',
      'Ust-Orda Buryat',
      'Yamalo-Nenets',
      'Altay',
      'Khabarovsk',
      'Krasnodar',
      'Krasnoyarsk',
      'Primorskiy',
      'Stavropol',
      'Moscow',
      'St. Petersburg',
      'Yevrey',
    ],
  },
  {
    countryName: 'Republic of Serbia',
    countryCode: '381',
    countryIsoCode: 'RS',
    states: ['Kosovo', 'Montenegro', 'Serbia', 'Vojvodina'],
  },
  {
    countryName: 'Slovakia',
    countryCode: '421',
    countryIsoCode: 'SK',
    states: [
      'Banskobystricky',
      'Bratislavsky',
      'Kosicky',
      'Nitriansky',
      'Presovsky',
      'Trenciansky',
      'Trnavsky',
      'Zilinsky',
    ],
  },
  {
    countryName: 'Slovenia',
    countryCode: '386',
    countryIsoCode: 'SI',
    states: [
      'Ajdovscina',
      'Beltinci',
      'Benedikt',
      'Bistrica ob Sotli',
      'Bled',
      'Bloke',
      'Bohinj',
      'Borovnica',
      'Bovec',
      'Braslovce',
      'Brda',
      'Brezice',
      'Brezovica',
      'Cankova',
      'Celje',
      'Cerklje na Gorenjskem',
      'Cerknica',
      'Cerkno',
      'Cerkvenjak',
      'Crensovci',
      'Crna na Koroskem',
      'Crnomelj',
      'Destrnik',
      'Divaca',
      'Dobje',
      'Dobrepolje',
      'Dobrna',
      'Dobrova-Horjul-Polhov Gradec',
      'Dobrovnik-Dobronak',
      'Dolenjske Toplice',
      'Dol pri Ljubljani',
      'Domzale',
      'Dornava',
      'Dravograd',
      'Duplek',
      'Gorenja Vas-Poljane',
      'Gorisnica',
      'Gornja Radgona',
      'Gornji Grad',
      'Gornji Petrovci',
      'Grad',
      'Grosuplje',
      'Hajdina',
      'Hoce-Slivnica',
      'Hodos-Hodos',
      'Horjul',
      'Hrastnik',
      'Hrpelje-Kozina',
      'Idrija',
      'Ig',
      'Ilirska Bistrica',
      'Ivancna Gorica',
      'Izola-Isola',
      'Jesenice',
      'Jezersko',
      'Jursinci',
      'Kamnik',
      'Kanal',
      'Kidricevo',
      'Kobarid',
      'Kobilje',
      'Kocevje',
      'Komen',
      'Komenda',
      'Koper-Capodistria',
      'Kostel',
      'Kozje',
      'Kranj',
      'Kranjska Gora',
      'Krizevci',
      'Krsko',
      'Kungota',
      'Kuzma',
      'Lasko',
      'Lenart',
      'Lendava-Lendva',
      'Litija',
      'Ljubljana',
      'Ljubno',
      'Ljutomer',
      'Logatec',
      'Loska Dolina',
      'Loski Potok',
      'Lovrenc na Pohorju',
      'Luce',
      'Lukovica',
      'Majsperk',
      'Maribor',
      'Markovci',
      'Medvode',
      'Menges',
      'Metlika',
      'Mezica',
      'Miklavz na Dravskem Polju',
      'Miren-Kostanjevica',
      'Mirna Pec',
      'Mislinja',
      'Moravce',
      'Moravske Toplice',
      'Mozirje',
      'Murska Sobota',
      'Muta',
      'Naklo',
      'Nazarje',
      'Nova Gorica',
      'Novo Mesto',
      'Odranci',
      'Oplotnica',
      'Ormoz',
      'Osilnica',
      'Pesnica',
      'Piran-Pirano',
      'Pivka',
      'Podcetrtek',
      'Podlehnik',
      'Podvelka',
      'Polzela',
      'Postojna',
      'Prebold',
      'Preddvor',
      'Prevalje',
      'Ptuj',
      'Puconci',
      'Race-Fram',
      'Radece',
      'Radenci',
      'Radlje ob Dravi',
      'Radovljica',
      'Ravne na Koroskem',
      'Razkrizje',
      'Ribnica',
      'Ribnica na Pohorju',
      'Rogasovci',
      'Rogaska Slatina',
      'Rogatec',
      'Ruse',
      'Salovci',
      'Selnica ob Dravi',
      'Semic',
      'Sempeter-Vrtojba',
      'Sencur',
      'Sentilj',
      'Sentjernej',
      'Sentjur pri Celju',
      'Sevnica',
      'Sezana',
      'Skocjan',
      'Skofja Loka',
      'Skofljica',
      'Slovenj Gradec',
      'Slovenska Bistrica',
      'Slovenske Konjice',
      'Smarje pri Jelsah',
      'Smartno ob Paki',
      'Smartno pri Litiji',
      'Sodrazica',
      'Solcava',
      'Sostanj',
      'Starse',
      'Store',
      'Sveta Ana',
      'Sveti Andraz v Slovenskih Goricah',
      'Sveti Jurij',
      'Tabor',
      'Tisina',
      'Tolmin',
      'Trbovlje',
      'Trebnje',
      'Trnovska Vas',
      'Trzic',
      'Trzin',
      'Turnisce',
      'Velenje',
      'Velika Polana',
      'Velike Lasce',
      'Verzej',
      'Videm',
      'Vipava',
      'Vitanje',
      'Vodice',
      'Vojnik',
      'Vransko',
      'Vrhnika',
      'Vuzenica',
      'Zagorje ob Savi',
      'Zalec',
      'Zavrc',
      'Zelezniki',
      'Zetale',
      'Ziri',
      'Zirovnica',
      'Zuzemberk',
      'Zrece',
    ],
  },
  {
    countryName: 'Ukraine',
    countryCode: '380',
    countryIsoCode: 'UA',
    states: [
      'Cherkasy',
      'Chernihiv',
      'Chernivtsi',
      'Crimea',
      'Dnipro',
      'Donetsk',
      'Ivano-Frankivsk',
      'Kharkiv',
      'Kherson',
      'Khmelnytskyi',
      'Kirovohrad',
      'Kyiv',
      'Luhansk',
      'Lviv',
      'Mykolayiv',
      'Odesa',
      'Poltava',
      'Rivne',
      'Sumy',
      'Ternopil',
      'Vinnytsya',
      'Volyn',
      'Zakarpattya',
      'Zaporizhzhya',
      'Zhytomyr',
    ],
  },
  {
    countryName: 'United Kingdom',
    countryCode: '44',
    countryIsoCode: 'GB',
    states: [
      'Aberdeenshire',
      'Angus',
      'Antrim',
      'Argyll',
      'Armagh',
      'Ayrshire',
      'Banffshire',
      'Berkshire',
      'Berwickshire',
      'Bristol',
      'Buckinghamshire',
      'Bute',
      'Caithness',
      'Cambridgeshire',
      'Cheshire',
      'City of London',
      'Clackmannanshire',
      'Clwyd',
      'Cornwall',
      'Cumbria',
      'Derbyshire',
      'Devon',
      'Dorset',
      'Down',
      'Dumfriesshire',
      'Dunbartonshire',
      'Durham',
      'Dyfed',
      'East Lothian',
      'East Riding of Yorkshire',
      'East Sussex',
      'Essex',
      'Fermanagh',
      'Fife',
      'Gloucestershire',
      'Greater London',
      'Greater Manchester',
      'Gwent',
      'Gwynedd',
      'Hampshire',
      'Herefordshire',
      'Hertfordshire',
      'Inverness-shire',
      'Isle of Wight',
      'Kent',
      'Kincardineshire',
      'Kinross-shire',
      'Kirkcudbrightshire',
      'Lanarkshire',
      'Lancashire',
      'Leicestershire',
      'Lincolnshire',
      'Londonderry',
      'Merseyside',
      'Mid Glamorgan',
      'Midlothian',
      'Moray',
      'Nairnshire',
      'Norfolk',
      'North Yorkshire',
      'Northamptonshire',
      'Northumberland',
      'Nottinghamshire',
      'Orkney',
      'Oxfordshire',
      'Peeblesshire',
      'Perthshire',
      'Powys',
      'Renfrewshire',
      'Ross and Cromarty',
      'Roxburghshire',
      'Rutland',
      'Selkirkshire',
      'Shetland',
      'Shropshire',
      'Somerset',
      'South Glamorgan',
      'South Yorkshire',
      'Staffordshire',
      'Stirlingshire',
      'Suffolk',
      'Surrey',
      'Sutherland',
      'Tyne and Wear',
      'Tyrone',
      'Warwickshire',
      'West Glamorgan',
      'West Lothian',
      'West Midlands',
      'West Sussex',
      'West Yorkshire',
      'Wigtownshire',
      'Wiltshire',
      'Worcestershire',
    ],
  },
  {
    countryName: 'United States',
    countryCode: '1',
    countryIsoCode: 'US',
    states: [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'District of Columbia',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
    ],
  },
  {
    countryName: 'Uzbekistan',
    countryCode: '998',
    countryIsoCode: 'UZ',
    states: [
      'Andijon Viloyati',
      'Buxoro Viloyati',
      'Fargona Viloyati',
      'Jizzax Viloyati',
      'Namangan Viloyati',
      'Navoiy Viloyati',
      'Qashqadaryo Viloyati',
      'Qaraqalpogiston Respublikasi',
      'Samarqand Viloyati',
      'Sirdaryo Viloyati',
      'Surxondaryo Viloyati',
      'Toshkent Shahri',
      'Toshkent Viloyati',
      'Xorazm Viloyati',
    ],
  },
  {
    countryName: 'Vietnam',
    countryCode: '84',
    countryIsoCode: 'VN',
    states: [
      'An Giang',
      'Bac Giang',
      'Bac Kan',
      'Bac Lieu',
      'Bac Ninh',
      'Ba Ria-Vung Tau',
      'Ben Tre',
      'Binh Dinh',
      'Binh Duong',
      'Binh Phuoc',
      'Binh Thuan',
      'Ca Mau',
      'Cao Bang',
      'Dac Lak',
      'Dac Nong',
      'Dien Bien',
      'Dong Nai',
      'Dong Thap',
      'Gia Lai',
      'Ha Giang',
      'Hai Duong',
      'Ha Nam',
      'Ha Tay',
      'Ha Tinh',
      'Hau Giang',
      'Hoa Binh',
      'Hung Yen',
      'Khanh Hoa',
      'Kien Giang',
      'Kon Tum',
      'Lai Chau',
      'Lam Dong',
      'Lang Son',
      'Lao Cai',
      'Long An',
      'Nam Dinh',
      'Nghe An',
      'Ninh Binh',
      'Ninh Thuan',
      'Phu Tho',
      'Phu Yen',
      'Quang Binh',
      'Quang Nam',
      'Quang Ngai',
      'Quang Ninh',
      'Quang Tri',
      'Soc Trang',
      'Son La',
      'Tay Ninh',
      'Thai Binh',
      'Thai Nguyen',
      'Thanh Hoa',
      'Thua Thien-Hue',
      'Tien Giang',
      'Tra Vinh',
      'Tuyen Quang',
      'Vinh Long',
      'Vinh Phuc',
      'Yen Bai',
      'Can Tho',
      'Da Nang',
      'Hai Phong',
      'Hanoi',
      'Ho Chi Minh',
    ],
  },
];

module.exports = { countriesWithCode };
