const timeZoneList = [
  {
    countryCode: 'CI',
    countryName: 'Cote dIvoire',
    timeZone: 'Africa/Abidjan',
    gmt: 'UTC',
  },
  { countryCode: 'GH', countryName: 'Ghana', timeZone: 'Africa/Accra', gmt: 'UTC' },
  {
    countryCode: 'ET',
    countryName: 'Ethiopia',
    timeZone: 'Africa/Addis_Ababa',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'DZ',
    countryName: 'Algeria',
    timeZone: 'Africa/Algiers',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'ER',
    countryName: 'Eritrea',
    timeZone: 'Africa/Asmara',
    gmt: 'UTC +03:00',
  },
  { countryCode: 'ML', countryName: 'Mali', timeZone: 'Africa/Bamako', gmt: 'UTC' },
  {
    countryCode: 'CF',
    countryName: 'Central African Republic',
    timeZone: 'Africa/Bangui',
    gmt: 'UTC +01:00',
  },
  { countryCode: 'GM', countryName: 'Gambia', timeZone: 'Africa/Banjul', gmt: 'UTC' },
  {
    countryCode: 'GW',
    countryName: 'Guinea-Bissau',
    timeZone: 'Africa/Bissau',
    gmt: 'UTC',
  },
  {
    countryCode: 'MW',
    countryName: 'Malawi',
    timeZone: 'Africa/Blantyre',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'CG',
    countryName: 'Congo',
    timeZone: 'Africa/Brazzaville',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'BI',
    countryName: 'Burundi',
    timeZone: 'Africa/Bujumbura',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'EG',
    countryName: 'Egypt',
    timeZone: 'Africa/Cairo',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'MA',
    countryName: 'Morocco',
    timeZone: 'Africa/Casablanca',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    timeZone: 'Africa/Ceuta',
    gmt: 'UTC +02:00',
  },
  { countryCode: 'GN', countryName: 'Guinea', timeZone: 'Africa/Conakry', gmt: 'UTC' },
  { countryCode: 'SN', countryName: 'Senegal', timeZone: 'Africa/Dakar', gmt: 'UTC' },
  {
    countryCode: 'TZ',
    countryName: 'Tanzania, United Republic of',
    timeZone: 'Africa/Dar_es_Salaam',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'DJ',
    countryName: 'Djibouti',
    timeZone: 'Africa/Djibouti',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'CM',
    countryName: 'Cameroon',
    timeZone: 'Africa/Douala',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'EH',
    countryName: 'Western Sahara',
    timeZone: 'Africa/El_Aaiun',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'SL',
    countryName: 'Sierra Leone',
    timeZone: 'Africa/Freetown',
    gmt: 'UTC',
  },
  {
    countryCode: 'BW',
    countryName: 'Botswana',
    timeZone: 'Africa/Gaborone',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'ZW',
    countryName: 'Zimbabwe',
    timeZone: 'Africa/Harare',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'ZA',
    countryName: 'South Africa',
    timeZone: 'Africa/Johannesburg',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'SS',
    countryName: 'South Sudan',
    timeZone: 'Africa/Juba',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'UG',
    countryName: 'Uganda',
    timeZone: 'Africa/Kampala',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'SD',
    countryName: 'Sudan',
    timeZone: 'Africa/Khartoum',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'RW',
    countryName: 'Rwanda',
    timeZone: 'Africa/Kigali',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'CD',
    countryName: 'Congo, the Democratic Republic of the',
    timeZone: 'Africa/Kinshasa',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'NG',
    countryName: 'Nigeria',
    timeZone: 'Africa/Lagos',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'GA',
    countryName: 'Gabon',
    timeZone: 'Africa/Libreville',
    gmt: 'UTC +01:00',
  },
  { countryCode: 'TG', countryName: 'Togo', timeZone: 'Africa/Lome', gmt: 'UTC' },
  {
    countryCode: 'AO',
    countryName: 'Angola',
    timeZone: 'Africa/Luanda',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'CD',
    countryName: 'Congo, the Democratic Republic of the',
    timeZone: 'Africa/Lubumbashi',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'ZM',
    countryName: 'Zambia',
    timeZone: 'Africa/Lusaka',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'GQ',
    countryName: 'Equatorial Guinea',
    timeZone: 'Africa/Malabo',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'MZ',
    countryName: 'Mozambique',
    timeZone: 'Africa/Maputo',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'LS',
    countryName: 'Lesotho',
    timeZone: 'Africa/Maseru',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'SZ',
    countryName: 'Swaziland',
    timeZone: 'Africa/Mbabane',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'SO',
    countryName: 'Somalia',
    timeZone: 'Africa/Mogadishu',
    gmt: 'UTC +03:00',
  },
  { countryCode: 'LR', countryName: 'Liberia', timeZone: 'Africa/Monrovia', gmt: 'UTC' },
  {
    countryCode: 'KE',
    countryName: 'Kenya',
    timeZone: 'Africa/Nairobi',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'TD',
    countryName: 'Chad',
    timeZone: 'Africa/Ndjamena',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'NE',
    countryName: 'Niger',
    timeZone: 'Africa/Niamey',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'MR',
    countryName: 'Mauritania',
    timeZone: 'Africa/Nouakchott',
    gmt: 'UTC',
  },
  {
    countryCode: 'BF',
    countryName: 'Burkina Faso',
    timeZone: 'Africa/Ouagadougou',
    gmt: 'UTC',
  },
  {
    countryCode: 'BJ',
    countryName: 'Benin',
    timeZone: 'Africa/Porto-Novo',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'ST',
    countryName: 'Sao Tome and Principe',
    timeZone: 'Africa/Sao_Tome',
    gmt: 'UTC',
  },
  {
    countryCode: 'LY',
    countryName: 'Libya',
    timeZone: 'Africa/Tripoli',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'TN',
    countryName: 'Tunisia',
    timeZone: 'Africa/Tunis',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'NA',
    countryName: 'Namibia',
    timeZone: 'Africa/Windhoek',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Adak',
    gmt: 'UTC -09:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Anchorage',
    gmt: 'UTC -08:00',
  },
  {
    countryCode: 'AI',
    countryName: 'Anguilla',
    timeZone: 'America/Anguilla',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'AG',
    countryName: 'Antigua and Barbuda',
    timeZone: 'America/Antigua',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Araguaina',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Buenos_Aires',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Catamarca',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Cordoba',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Jujuy',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/La_Rioja',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Mendoza',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Rio_Gallegos',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Salta',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/San_Juan',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/San_Luis',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Tucuman',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Ushuaia',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AW',
    countryName: 'Aruba',
    timeZone: 'America/Aruba',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'PY',
    countryName: 'Paraguay',
    timeZone: 'America/Asuncion',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Atikokan',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Bahia',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Bahia_Banderas',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'BB',
    countryName: 'Barbados',
    timeZone: 'America/Barbados',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Belem',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'BZ',
    countryName: 'Belize',
    timeZone: 'America/Belize',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Blanc-Sablon',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Boa_Vista',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'CO',
    countryName: 'Colombia',
    timeZone: 'America/Bogota',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Boise',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Cambridge_Bay',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Campo_Grande',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Cancun',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'VE',
    countryName: 'Venezuela, Bolivarian Republic of',
    timeZone: 'America/Caracas',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'GF',
    countryName: 'French Guiana',
    timeZone: 'America/Cayenne',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'KY',
    countryName: 'Cayman Islands',
    timeZone: 'America/Cayman',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Chicago',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Chihuahua',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'CR',
    countryName: 'Costa Rica',
    timeZone: 'America/Costa_Rica',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Creston',
    gmt: 'UTC -07:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Cuiaba',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'CW',
    countryName: 'Curacao',
    timeZone: 'America/Curacao',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'GL',
    countryName: 'Greenland',
    timeZone: 'America/Danmarkshavn',
    gmt: 'UTC',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Dawson',
    gmt: 'UTC -07:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Dawson_Creek',
    gmt: 'UTC -07:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Denver',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Detroit',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'DM',
    countryName: 'Dominica',
    timeZone: 'America/Dominica',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Edmonton',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Eirunepe',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'SV',
    countryName: 'El Salvador',
    timeZone: 'America/El_Salvador',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Fort_Nelson',
    gmt: 'UTC -07:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Fortaleza',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Glace_Bay',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Goose_Bay',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'TC',
    countryName: 'Turks and Caicos Islands',
    timeZone: 'America/Grand_Turk',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'GD',
    countryName: 'Grenada',
    timeZone: 'America/Grenada',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'GP',
    countryName: 'Guadeloupe',
    timeZone: 'America/Guadeloupe',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'GT',
    countryName: 'Guatemala',
    timeZone: 'America/Guatemala',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'EC',
    countryName: 'Ecuador',
    timeZone: 'America/Guayaquil',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'GY',
    countryName: 'Guyana',
    timeZone: 'America/Guyana',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Halifax',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'CU',
    countryName: 'Cuba',
    timeZone: 'America/Havana',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Hermosillo',
    gmt: 'UTC -07:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Indianapolis',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Knox',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Marengo',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Petersburg',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Tell_City',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Vevay',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Vincennes',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Winamac',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Inuvik',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Iqaluit',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'JM',
    countryName: 'Jamaica',
    timeZone: 'America/Jamaica',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Juneau',
    gmt: 'UTC -08:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Kentucky/Louisville',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Kentucky/Monticello',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'BQ',
    countryName: 'Bonaire, Sint Eustatius and Saba',
    timeZone: 'America/Kralendijk',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'BO',
    countryName: 'Bolivia, Plurinational State of',
    timeZone: 'America/La_Paz',
    gmt: 'UTC -04:00',
  },
  { countryCode: 'PE', countryName: 'Peru', timeZone: 'America/Lima', gmt: 'UTC -05:00' },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Los_Angeles',
    gmt: 'UTC -07:00',
  },
  {
    countryCode: 'SX',
    countryName: 'Sint Maarten (Dutch part)',
    timeZone: 'America/Lower_Princes',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Maceio',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'NI',
    countryName: 'Nicaragua',
    timeZone: 'America/Managua',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Manaus',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'MF',
    countryName: 'Saint Martin (French part)',
    timeZone: 'America/Marigot',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'MQ',
    countryName: 'Martinique',
    timeZone: 'America/Martinique',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Matamoros',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Mazatlan',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Menominee',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Merida',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Metlakatla',
    gmt: 'UTC -08:00',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Mexico_City',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'PM',
    countryName: 'Saint Pierre and Miquelon',
    timeZone: 'America/Miquelon',
    gmt: 'UTC -02:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Moncton',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Monterrey',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'UY',
    countryName: 'Uruguay',
    timeZone: 'America/Montevideo',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'MS',
    countryName: 'Montserrat',
    timeZone: 'America/Montserrat',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'BS',
    countryName: 'Bahamas',
    timeZone: 'America/Nassau',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/New_York',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Nipigon',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Nome',
    gmt: 'UTC -08:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Noronha',
    gmt: 'UTC -02:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/North_Dakota/Beulah',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/North_Dakota/Center',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/North_Dakota/New_Salem',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'GL',
    countryName: 'Greenland',
    timeZone: 'America/Nuuk',
    gmt: 'UTC -02:00',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Ojinaga',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'PA',
    countryName: 'Panama',
    timeZone: 'America/Panama',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Pangnirtung',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'SR',
    countryName: 'Suriname',
    timeZone: 'America/Paramaribo',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Phoenix',
    gmt: 'UTC -07:00',
  },
  {
    countryCode: 'TT',
    countryName: 'Trinidad and Tobago',
    timeZone: 'America/Port_of_Spain',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'HT',
    countryName: 'Haiti',
    timeZone: 'America/Port-au-Prince',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Porto_Velho',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'PR',
    countryName: 'Puerto Rico',
    timeZone: 'America/Puerto_Rico',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'CL',
    countryName: 'Chile',
    timeZone: 'America/Punta_Arenas',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Rainy_River',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Rankin_Inlet',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Recife',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Regina',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Resolute',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Rio_Branco',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Santarem',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'CL',
    countryName: 'Chile',
    timeZone: 'America/Santiago',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'DO',
    countryName: 'Dominican Republic',
    timeZone: 'America/Santo_Domingo',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Sao_Paulo',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'GL',
    countryName: 'Greenland',
    timeZone: 'America/Scoresbysund',
    gmt: 'UTC',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Sitka',
    gmt: 'UTC -08:00',
  },
  {
    countryCode: 'BL',
    countryName: 'Saint Barthélemy',
    timeZone: 'America/St_Barthelemy',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/St_Johns',
    gmt: 'UTC -02:30',
  },
  {
    countryCode: 'KN',
    countryName: 'Saint Kitts and Nevis',
    timeZone: 'America/St_Kitts',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'LC',
    countryName: 'Saint Lucia',
    timeZone: 'America/St_Lucia',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'VI',
    countryName: 'Virgin Islands, U.S.',
    timeZone: 'America/St_Thomas',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'VC',
    countryName: 'Saint Vincent and the Grenadines',
    timeZone: 'America/St_Vincent',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Swift_Current',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'HN',
    countryName: 'Honduras',
    timeZone: 'America/Tegucigalpa',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'GL',
    countryName: 'Greenland',
    timeZone: 'America/Thule',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Thunder_Bay',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Tijuana',
    gmt: 'UTC -07:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Toronto',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'VG',
    countryName: 'Virgin Islands, British',
    timeZone: 'America/Tortola',
    gmt: 'UTC -04:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Vancouver',
    gmt: 'UTC -07:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Whitehorse',
    gmt: 'UTC -07:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Winnipeg',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Yakutat',
    gmt: 'UTC -08:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Yellowknife',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Casey',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Davis',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/DumontDUrville',
    gmt: 'UTC +10:00',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Antarctica/Macquarie',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Mawson',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/McMurdo',
    gmt: 'UTC +13:00',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Palmer',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Rothera',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Syowa',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Troll',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Vostok',
    gmt: 'UTC +06:00',
  },
  {
    countryCode: 'SJ',
    countryName: 'Svalbard and Jan Mayen',
    timeZone: 'Arctic/Longyearbyen',
    gmt: 'UTC +02:00',
  },
  { countryCode: 'YE', countryName: 'Yemen', timeZone: 'Asia/Aden', gmt: 'UTC +03:00' },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Almaty',
    gmt: 'UTC +06:00',
  },
  { countryCode: 'JO', countryName: 'Jordan', timeZone: 'Asia/Amman', gmt: 'UTC +03:00' },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Anadyr',
    gmt: 'UTC +12:00',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Aqtau',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Aqtobe',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'TM',
    countryName: 'Turkmenistan',
    timeZone: 'Asia/Ashgabat',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Atyrau',
    gmt: 'UTC +05:00',
  },
  { countryCode: 'IQ', countryName: 'Iraq', timeZone: 'Asia/Baghdad', gmt: 'UTC +03:00' },
  {
    countryCode: 'BH',
    countryName: 'Bahrain',
    timeZone: 'Asia/Bahrain',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    timeZone: 'Asia/Baku',
    gmt: 'UTC +04:00',
  },
  {
    countryCode: 'TH',
    countryName: 'Thailand',
    timeZone: 'Asia/Bangkok',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Barnaul',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'LB',
    countryName: 'Lebanon',
    timeZone: 'Asia/Beirut',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'KG',
    countryName: 'Kyrgyzstan',
    timeZone: 'Asia/Bishkek',
    gmt: 'UTC +06:00',
  },
  {
    countryCode: 'BN',
    countryName: 'Brunei Darussalam',
    timeZone: 'Asia/Brunei',
    gmt: 'UTC +08:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Chita',
    gmt: 'UTC +09:00',
  },
  {
    countryCode: 'MN',
    countryName: 'Mongolia',
    timeZone: 'Asia/Choibalsan',
    gmt: 'UTC +08:00',
  },
  {
    countryCode: 'LK',
    countryName: 'Sri Lanka',
    timeZone: 'Asia/Colombo',
    gmt: 'UTC +05:30',
  },
  {
    countryCode: 'SY',
    countryName: 'Syrian Arab Republic',
    timeZone: 'Asia/Damascus',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'BD',
    countryName: 'Bangladesh',
    timeZone: 'Asia/Dhaka',
    gmt: 'UTC +06:00',
  },
  {
    countryCode: 'TL',
    countryName: 'Timor-Leste',
    timeZone: 'Asia/Dili',
    gmt: 'UTC +09:00',
  },
  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    timeZone: 'Asia/Dubai',
    gmt: 'UTC +04:00',
  },
  {
    countryCode: 'TJ',
    countryName: 'Tajikistan',
    timeZone: 'Asia/Dushanbe',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'CY',
    countryName: 'Cyprus',
    timeZone: 'Asia/Famagusta',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'PS',
    countryName: 'Palestine, State of',
    timeZone: 'Asia/Gaza',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'PS',
    countryName: 'Palestine, State of',
    timeZone: 'Asia/Hebron',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'VN',
    countryName: 'Viet Nam',
    timeZone: 'Asia/Ho_Chi_Minh',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'HK',
    countryName: 'Hong Kong',
    timeZone: 'Asia/Hong_Kong',
    gmt: 'UTC +08:00',
  },
  {
    countryCode: 'MN',
    countryName: 'Mongolia',
    timeZone: 'Asia/Hovd',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Irkutsk',
    gmt: 'UTC +08:00',
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    timeZone: 'Asia/Jakarta',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    timeZone: 'Asia/Jayapura',
    gmt: 'UTC +09:00',
  },
  {
    countryCode: 'IL',
    countryName: 'Israel',
    timeZone: 'Asia/Jerusalem',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'AF',
    countryName: 'Afghanistan',
    timeZone: 'Asia/Kabul',
    gmt: 'UTC +04:30',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Kamchatka',
    gmt: 'UTC +12:00',
  },
  {
    countryCode: 'PK',
    countryName: 'Pakistan',
    timeZone: 'Asia/Karachi',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'NP',
    countryName: 'Nepal',
    timeZone: 'Asia/Kathmandu',
    gmt: 'UTC +05:45',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Khandyga',
    gmt: 'UTC +09:00',
  },
  {
    countryCode: 'IN',
    countryName: 'India',
    timeZone: 'Asia/Kolkata',
    gmt: 'UTC +05:30',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Krasnoyarsk',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'MY',
    countryName: 'Malaysia',
    timeZone: 'Asia/Kuala_Lumpur',
    gmt: 'UTC +08:00',
  },
  {
    countryCode: 'MY',
    countryName: 'Malaysia',
    timeZone: 'Asia/Kuching',
    gmt: 'UTC +08:00',
  },
  {
    countryCode: 'KW',
    countryName: 'Kuwait',
    timeZone: 'Asia/Kuwait',
    gmt: 'UTC +03:00',
  },
  { countryCode: 'MO', countryName: 'Macao', timeZone: 'Asia/Macau', gmt: 'UTC +08:00' },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Magadan',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    timeZone: 'Asia/Makassar',
    gmt: 'UTC +08:00',
  },
  {
    countryCode: 'PH',
    countryName: 'Philippines',
    timeZone: 'Asia/Manila',
    gmt: 'UTC +08:00',
  },
  { countryCode: 'OM', countryName: 'Oman', timeZone: 'Asia/Muscat', gmt: 'UTC +04:00' },
  {
    countryCode: 'CY',
    countryName: 'Cyprus',
    timeZone: 'Asia/Nicosia',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Novokuznetsk',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Novosibirsk',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Omsk',
    gmt: 'UTC +06:00',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Oral',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'KH',
    countryName: 'Cambodia',
    timeZone: 'Asia/Phnom_Penh',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    timeZone: 'Asia/Pontianak',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'KP',
    countryName: 'Korea, Democratic Peoples Republic of',
    timeZone: 'Asia/Pyongyang',
    gmt: 'UTC +09:00',
  },
  { countryCode: 'QA', countryName: 'Qatar', timeZone: 'Asia/Qatar', gmt: 'UTC +03:00' },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Qostanay',
    gmt: 'UTC +06:00',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Qyzylorda',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    timeZone: 'Asia/Riyadh',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Sakhalin',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    timeZone: 'Asia/Samarkand',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'KR',
    countryName: 'Korea, Republic of',
    timeZone: 'Asia/Seoul',
    gmt: 'UTC +09:00',
  },
  {
    countryCode: 'CN',
    countryName: 'China',
    timeZone: 'Asia/Shanghai',
    gmt: 'UTC +08:00',
  },
  {
    countryCode: 'SG',
    countryName: 'Singapore',
    timeZone: 'Asia/Singapore',
    gmt: 'UTC +08:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Srednekolymsk',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'TW',
    countryName: 'Taiwan, Province of China',
    timeZone: 'Asia/Taipei',
    gmt: 'UTC +08:00',
  },
  {
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    timeZone: 'Asia/Tashkent',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'GE',
    countryName: 'Georgia',
    timeZone: 'Asia/Tbilisi',
    gmt: 'UTC +04:00',
  },
  {
    countryCode: 'IR',
    countryName: 'Iran, Islamic Republic of',
    timeZone: 'Asia/Tehran',
    gmt: 'UTC +03:30',
  },
  {
    countryCode: 'BT',
    countryName: 'Bhutan',
    timeZone: 'Asia/Thimphu',
    gmt: 'UTC +06:00',
  },
  { countryCode: 'JP', countryName: 'Japan', timeZone: 'Asia/Tokyo', gmt: 'UTC +09:00' },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Tomsk',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'MN',
    countryName: 'Mongolia',
    timeZone: 'Asia/Ulaanbaatar',
    gmt: 'UTC +08:00',
  },
  { countryCode: 'CN', countryName: 'China', timeZone: 'Asia/Urumqi', gmt: 'UTC +06:00' },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Ust-Nera',
    gmt: 'UTC +10:00',
  },
  {
    countryCode: 'LA',
    countryName: 'Lao Peoples Democratic Republic',
    timeZone: 'Asia/Vientiane',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Vladivostok',
    gmt: 'UTC +10:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Yakutsk',
    gmt: 'UTC +09:00',
  },
  {
    countryCode: 'MM',
    countryName: 'Myanmar',
    timeZone: 'Asia/Yangon',
    gmt: 'UTC +06:30',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Yekaterinburg',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'AM',
    countryName: 'Armenia',
    timeZone: 'Asia/Yerevan',
    gmt: 'UTC +04:00',
  },
  { countryCode: 'PT', countryName: 'Portugal', timeZone: 'Atlantic/Azores', gmt: 'UTC' },
  {
    countryCode: 'BM',
    countryName: 'Bermuda',
    timeZone: 'Atlantic/Bermuda',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    timeZone: 'Atlantic/Canary',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'CV',
    countryName: 'Cape Verde',
    timeZone: 'Atlantic/Cape_Verde',
    gmt: 'UTC -01:00',
  },
  {
    countryCode: 'FO',
    countryName: 'Faroe Islands',
    timeZone: 'Atlantic/Faroe',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'PT',
    countryName: 'Portugal',
    timeZone: 'Atlantic/Madeira',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'IS',
    countryName: 'Iceland',
    timeZone: 'Atlantic/Reykjavik',
    gmt: 'UTC',
  },
  {
    countryCode: 'GS',
    countryName: 'South Georgia and the South Sandwich Islands',
    timeZone: 'Atlantic/South_Georgia',
    gmt: 'UTC -02:00',
  },
  {
    countryCode: 'SH',
    countryName: 'Saint Helena, Ascension and Tristan da Cunha',
    timeZone: 'Atlantic/St_Helena',
    gmt: 'UTC',
  },
  {
    countryCode: 'FK',
    countryName: 'Falkland Islands (Malvinas)',
    timeZone: 'Atlantic/Stanley',
    gmt: 'UTC -03:00',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Adelaide',
    gmt: 'UTC +10:30',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Brisbane',
    gmt: 'UTC +10:00',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Broken_Hill',
    gmt: 'UTC +10:30',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Currie',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Darwin',
    gmt: 'UTC +09:30',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Eucla',
    gmt: 'UTC +08:45',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Hobart',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Lindeman',
    gmt: 'UTC +10:00',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Lord_Howe',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Melbourne',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Perth',
    gmt: 'UTC +08:00',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Sydney',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'NL',
    countryName: 'Netherlands',
    timeZone: 'Europe/Amsterdam',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'AD',
    countryName: 'Andorra',
    timeZone: 'Europe/Andorra',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Astrakhan',
    gmt: 'UTC +04:00',
  },
  {
    countryCode: 'GR',
    countryName: 'Greece',
    timeZone: 'Europe/Athens',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'RS',
    countryName: 'Serbia',
    timeZone: 'Europe/Belgrade',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    timeZone: 'Europe/Berlin',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'SK',
    countryName: 'Slovakia',
    timeZone: 'Europe/Bratislava',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'BE',
    countryName: 'Belgium',
    timeZone: 'Europe/Brussels',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'RO',
    countryName: 'Romania',
    timeZone: 'Europe/Bucharest',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'HU',
    countryName: 'Hungary',
    timeZone: 'Europe/Budapest',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    timeZone: 'Europe/Busingen',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'MD',
    countryName: 'Moldova, Republic of',
    timeZone: 'Europe/Chisinau',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'DK',
    countryName: 'Denmark',
    timeZone: 'Europe/Copenhagen',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'IE',
    countryName: 'Ireland',
    timeZone: 'Europe/Dublin',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'GI',
    countryName: 'Gibraltar',
    timeZone: 'Europe/Gibraltar',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'GG',
    countryName: 'Guernsey',
    timeZone: 'Europe/Guernsey',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'FI',
    countryName: 'Finland',
    timeZone: 'Europe/Helsinki',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'IM',
    countryName: 'Isle of Man',
    timeZone: 'Europe/Isle_of_Man',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'TR',
    countryName: 'Turkey',
    timeZone: 'Europe/Istanbul',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'JE',
    countryName: 'Jersey',
    timeZone: 'Europe/Jersey',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Kaliningrad',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'UA',
    countryName: 'Ukraine',
    timeZone: 'Europe/Kiev',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Kirov',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'PT',
    countryName: 'Portugal',
    timeZone: 'Europe/Lisbon',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'SI',
    countryName: 'Slovenia',
    timeZone: 'Europe/Ljubljana',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    timeZone: 'Europe/London',
    gmt: 'UTC +01:00',
  },
  {
    countryCode: 'LU',
    countryName: 'Luxembourg',
    timeZone: 'Europe/Luxembourg',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    timeZone: 'Europe/Madrid',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'MT',
    countryName: 'Malta',
    timeZone: 'Europe/Malta',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'AX',
    countryName: 'Aland Islands',
    timeZone: 'Europe/Mariehamn',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'BY',
    countryName: 'Belarus',
    timeZone: 'Europe/Minsk',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'MC',
    countryName: 'Monaco',
    timeZone: 'Europe/Monaco',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Moscow',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'NO',
    countryName: 'Norway',
    timeZone: 'Europe/Oslo',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'FR',
    countryName: 'France',
    timeZone: 'Europe/Paris',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'ME',
    countryName: 'Montenegro',
    timeZone: 'Europe/Podgorica',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'CZ',
    countryName: 'Czech Republic',
    timeZone: 'Europe/Prague',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'LV',
    countryName: 'Latvia',
    timeZone: 'Europe/Riga',
    gmt: 'UTC +03:00',
  },
  { countryCode: 'IT', countryName: 'Italy', timeZone: 'Europe/Rome', gmt: 'UTC +02:00' },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Samara',
    gmt: 'UTC +04:00',
  },
  {
    countryCode: 'SM',
    countryName: 'San Marino',
    timeZone: 'Europe/San_Marino',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'BA',
    countryName: 'Bosnia and Herzegovina',
    timeZone: 'Europe/Sarajevo',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Saratov',
    gmt: 'UTC +04:00',
  },
  {
    countryCode: 'UA',
    countryName: 'Ukraine',
    timeZone: 'Europe/Simferopol',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'MK',
    countryName: 'Macedonia, the Former Yugoslav Republic of',
    timeZone: 'Europe/Skopje',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'BG',
    countryName: 'Bulgaria',
    timeZone: 'Europe/Sofia',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'SE',
    countryName: 'Sweden',
    timeZone: 'Europe/Stockholm',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'EE',
    countryName: 'Estonia',
    timeZone: 'Europe/Tallinn',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'AL',
    countryName: 'Albania',
    timeZone: 'Europe/Tirane',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Ulyanovsk',
    gmt: 'UTC +04:00',
  },
  {
    countryCode: 'UA',
    countryName: 'Ukraine',
    timeZone: 'Europe/Uzhgorod',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'LI',
    countryName: 'Liechtenstein',
    timeZone: 'Europe/Vaduz',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'VA',
    countryName: 'Holy See (Vatican City State)',
    timeZone: 'Europe/Vatican',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'AT',
    countryName: 'Austria',
    timeZone: 'Europe/Vienna',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'LT',
    countryName: 'Lithuania',
    timeZone: 'Europe/Vilnius',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Volgograd',
    gmt: 'UTC +04:00',
  },
  {
    countryCode: 'PL',
    countryName: 'Poland',
    timeZone: 'Europe/Warsaw',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'HR',
    countryName: 'Croatia',
    timeZone: 'Europe/Zagreb',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'UA',
    countryName: 'Ukraine',
    timeZone: 'Europe/Zaporozhye',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'CH',
    countryName: 'Switzerland',
    timeZone: 'Europe/Zurich',
    gmt: 'UTC +02:00',
  },
  {
    countryCode: 'MG',
    countryName: 'Madagascar',
    timeZone: 'Indian/Antananarivo',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'IO',
    countryName: 'British Indian Ocean Territory',
    timeZone: 'Indian/Chagos',
    gmt: 'UTC +06:00',
  },
  {
    countryCode: 'CX',
    countryName: 'Christmas Island',
    timeZone: 'Indian/Christmas',
    gmt: 'UTC +07:00',
  },
  {
    countryCode: 'CC',
    countryName: 'Cocos (Keeling) Islands',
    timeZone: 'Indian/Cocos',
    gmt: 'UTC +06:30',
  },
  {
    countryCode: 'KM',
    countryName: 'Comoros',
    timeZone: 'Indian/Comoro',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'TF',
    countryName: 'French Southern Territories',
    timeZone: 'Indian/Kerguelen',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'SC',
    countryName: 'Seychelles',
    timeZone: 'Indian/Mahe',
    gmt: 'UTC +04:00',
  },
  {
    countryCode: 'MV',
    countryName: 'Maldives',
    timeZone: 'Indian/Maldives',
    gmt: 'UTC +05:00',
  },
  {
    countryCode: 'MU',
    countryName: 'Mauritius',
    timeZone: 'Indian/Mauritius',
    gmt: 'UTC +04:00',
  },
  {
    countryCode: 'YT',
    countryName: 'Mayotte',
    timeZone: 'Indian/Mayotte',
    gmt: 'UTC +03:00',
  },
  {
    countryCode: 'RE',
    countryName: 'Reunion',
    timeZone: 'Indian/Reunion',
    gmt: 'UTC +04:00',
  },
  {
    countryCode: 'WS',
    countryName: 'Samoa',
    timeZone: 'Pacific/Apia',
    gmt: 'UTC +14:00',
  },
  {
    countryCode: 'NZ',
    countryName: 'New Zealand',
    timeZone: 'Pacific/Auckland',
    gmt: 'UTC +13:00',
  },
  {
    countryCode: 'PG',
    countryName: 'Papua New Guinea',
    timeZone: 'Pacific/Bougainville',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'NZ',
    countryName: 'New Zealand',
    timeZone: 'Pacific/Chatham',
    gmt: 'UTC +13:45',
  },
  {
    countryCode: 'FM',
    countryName: 'Micronesia, Federated States of',
    timeZone: 'Pacific/Chuuk',
    gmt: 'UTC +10:00',
  },
  {
    countryCode: 'CL',
    countryName: 'Chile',
    timeZone: 'Pacific/Easter',
    gmt: 'UTC -05:00',
  },
  {
    countryCode: 'VU',
    countryName: 'Vanuatu',
    timeZone: 'Pacific/Efate',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'KI',
    countryName: 'Kiribati',
    timeZone: 'Pacific/Enderbury',
    gmt: 'UTC +13:00',
  },
  {
    countryCode: 'TK',
    countryName: 'Tokelau',
    timeZone: 'Pacific/Fakaofo',
    gmt: 'UTC +13:00',
  },
  { countryCode: 'FJ', countryName: 'Fiji', timeZone: 'Pacific/Fiji', gmt: 'UTC +12:00' },
  {
    countryCode: 'TV',
    countryName: 'Tuvalu',
    timeZone: 'Pacific/Funafuti',
    gmt: 'UTC +12:00',
  },
  {
    countryCode: 'EC',
    countryName: 'Ecuador',
    timeZone: 'Pacific/Galapagos',
    gmt: 'UTC -06:00',
  },
  {
    countryCode: 'PF',
    countryName: 'French Polynesia',
    timeZone: 'Pacific/Gambier',
    gmt: 'UTC -09:00',
  },
  {
    countryCode: 'SB',
    countryName: 'Solomon Islands',
    timeZone: 'Pacific/Guadalcanal',
    gmt: 'UTC +11:00',
  },
  { countryCode: 'GU', countryName: 'Guam', timeZone: 'Pacific/Guam', gmt: 'UTC +10:00' },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'Pacific/Honolulu',
    gmt: 'UTC -10:00',
  },
  {
    countryCode: 'KI',
    countryName: 'Kiribati',
    timeZone: 'Pacific/Kiritimati',
    gmt: 'UTC +14:00',
  },
  {
    countryCode: 'FM',
    countryName: 'Micronesia, Federated States of',
    timeZone: 'Pacific/Kosrae',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'MH',
    countryName: 'Marshall Islands',
    timeZone: 'Pacific/Kwajalein',
    gmt: 'UTC +12:00',
  },
  {
    countryCode: 'MH',
    countryName: 'Marshall Islands',
    timeZone: 'Pacific/Majuro',
    gmt: 'UTC +12:00',
  },
  {
    countryCode: 'PF',
    countryName: 'French Polynesia',
    timeZone: 'Pacific/Marquesas',
    gmt: 'UTC -09:30',
  },
  {
    countryCode: 'UM',
    countryName: 'United States Minor Outlying Islands',
    timeZone: 'Pacific/Midway',
    gmt: 'UTC -11:00',
  },
  {
    countryCode: 'NR',
    countryName: 'Nauru',
    timeZone: 'Pacific/Nauru',
    gmt: 'UTC +12:00',
  },
  { countryCode: 'NU', countryName: 'Niue', timeZone: 'Pacific/Niue', gmt: 'UTC -11:00' },
  {
    countryCode: 'NF',
    countryName: 'Norfolk Island',
    timeZone: 'Pacific/Norfolk',
    gmt: 'UTC +12:00',
  },
  {
    countryCode: 'NC',
    countryName: 'New Caledonia',
    timeZone: 'Pacific/Noumea',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'AS',
    countryName: 'American Samoa',
    timeZone: 'Pacific/Pago_Pago',
    gmt: 'UTC -11:00',
  },
  {
    countryCode: 'PW',
    countryName: 'Palau',
    timeZone: 'Pacific/Palau',
    gmt: 'UTC +09:00',
  },
  {
    countryCode: 'PN',
    countryName: 'Pitcairn',
    timeZone: 'Pacific/Pitcairn',
    gmt: 'UTC -08:00',
  },
  {
    countryCode: 'FM',
    countryName: 'Micronesia, Federated States of',
    timeZone: 'Pacific/Pohnpei',
    gmt: 'UTC +11:00',
  },
  {
    countryCode: 'PG',
    countryName: 'Papua New Guinea',
    timeZone: 'Pacific/Port_Moresby',
    gmt: 'UTC +10:00',
  },
  {
    countryCode: 'CK',
    countryName: 'Cook Islands',
    timeZone: 'Pacific/Rarotonga',
    gmt: 'UTC -10:00',
  },
  {
    countryCode: 'MP',
    countryName: 'Northern Mariana Islands',
    timeZone: 'Pacific/Saipan',
    gmt: 'UTC +10:00',
  },
  {
    countryCode: 'PF',
    countryName: 'French Polynesia',
    timeZone: 'Pacific/Tahiti',
    gmt: 'UTC -10:00',
  },
  {
    countryCode: 'KI',
    countryName: 'Kiribati',
    timeZone: 'Pacific/Tarawa',
    gmt: 'UTC +12:00',
  },
  {
    countryCode: 'TO',
    countryName: 'Tonga',
    timeZone: 'Pacific/Tongatapu',
    gmt: 'UTC +13:00',
  },
  {
    countryCode: 'UM',
    countryName: 'United States Minor Outlying Islands',
    timeZone: 'Pacific/Wake',
    gmt: 'UTC +12:00',
  },
  {
    countryCode: 'WF',
    countryName: 'Wallis and Futuna',
    timeZone: 'Pacific/Wallis',
    gmt: 'UTC +12:00',
  },
];

module.exports = { timeZoneList };
