const fakeRouter = require('../_fake/Routes');
const analyticsRouter = require('../analytics/Routes');
const userRouter = require('../user/userRoutes');
const infoRouter = require('../info/infoRoutes');
const serviceRouter = require('../service/serviceRoutes');
const baseRouter = require('../_base/Routes');
const classesRouter = require('../classes/Routes');
const eventRouter = require('../event/Routes');
const styleRouter = require('../style/Routes');
const classTypeRouter = require('../classType/Routes');
const listRouter = require('../lists/Routes');
const teacherAccountRouter = require('../teacherAccount/Routes');
const studentAccountRouter = require('../studentAccount/Routes');
const messageRouter = require('../telephony/message/Routes');
const callsRouter = require('../telephony/calls/Routes');
const clientRouter = require('../client/Routes');
const sipPhoneRouter = require('../sipPhone/Routes');
const paymentRouter = require('../payment/Routes');
const emailRouter = require('../_email/Routes');

module.exports = function routes(app) {
  app.use('/base', baseRouter);
  app.use('/user', userRouter);
  app.use('/classType', classTypeRouter);
  app.use('/classes', classesRouter);
  app.use('/event', eventRouter);
  app.use('/style', styleRouter);
  app.use('/fake', fakeRouter);
  app.use('/analytics', analyticsRouter);
  app.use('/teacherAccount', teacherAccountRouter);
  app.use('/studentAccount', studentAccountRouter);
  app.use('/client', clientRouter);
  app.use('/payment', paymentRouter);
  app.use('/info', infoRouter);
  app.use('/service', serviceRouter);
  app.use('/list', listRouter);
  app.use('/sipPhone', sipPhoneRouter);
  app.use('/telephony/message', messageRouter);
  app.use('/telephony/calls', callsRouter);
  app.use('/email', emailRouter);
};
